server:
  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
      username: user
      password: password
      authentication-database: admin
  kafka:
    bootstrap-servers: localhost:9092

management:
  tracing:
    sampling:
      probability: 1.0