server:
  port: 8081

demo:
  url: https://jsonplaceholder.typicode.com/posts/1

spring:
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret-key: 3f7a9b2e5c8d1f6g4h0i9j2k5l7m8n1o3p6q9r2s4t7u0v1w5x8y2z
  expiration: 900000

notification-service:
  url: http://NOTIFICATION-SERVICE

eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/