spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev_db
    username: mem_db
    password: password

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

eureka:
  instance:
    hostname: localhost